version: '2'

services:
  unobtanium:
    extends:
      file: docker-compose.tmpl.yml
      service: unobtanium-base-mainnet

  unobtanium-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: unobtanium-base-testnet

  addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-mainnet

  addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-testnet

  unoparty:
    extends:
      file: docker-compose.tmpl.yml
      service: unoparty-base-mainnet
    links:
      - unobtanium
      - addrindexrs

  unoparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: unoparty-base-testnet
    links:
      - unobtanium-testnet
      - addrindexrs-testnet

volumes:
  unobtanium-data:
  addrindexrs-data:
  unoparty-data:
