version: '2'

services:
  addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-mainnet

  addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-testnet

  unoparty:
    extends:
      file: docker-compose.tmpl.yml
      service: unoparty-base-mainnet
    links:
      - addrindexrs

  unoparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: unoparty-base-testnet
    links:
      - addrindexrs-testnet

volumes:
  addrindexrs-data:
  unoparty-data:
